name: ChunkyCiv
main: org.getchunky.chunkyciv.ChunkyCiv
version: b${build.number}
author: dumptruckman

depends: [Chunky]

permissions:
    chunkyciv.nation.create:
        description: Allows players to create nations.
        default: op