name: PluginTemplate
main: com.dumptruckman.plugintemplate.TemplatePlugin
version: b${build.number}
author: dumptruckman

depends: [Chunky]

permissions:
    chunkyciv.nation.create:
        description: Allows players to create nations.
        default: op